services:
  - type: web
    name: halawani-clinic
    runtime: node
    plan: free
    buildCommand: NODE_OPTIONS=--max-old-space-size=400 npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: halawani-db
      mountPath: /data
      sizeGB: 1
